In [13]:
import cv2
import numpy as np

In [14]:
img=cv2.imread("nature.jpeg")

In [35]:
img_re=cv2.resize(img,(500,500))

In [4]:
ker=np.ones((3,3),float)/9
 

In [5]:
print(ker)

[[0.11111111 0.11111111 0.11111111]
 [0.11111111 0.11111111 0.11111111]
 [0.11111111 0.11111111 0.11111111]]


In [6]:
tdf=cv2.filter2D(img_re,-1,ker)


In [7]:
cv2.imshow("image",img_re)
cv2.waitKey(0)
cv2.imshow("2d",tdf)
cv2.waitKey(0)
cv2.destroyAllWindows()

average blur

In [8]:
avg=cv2.blur(img_re,(25,25))

In [10]:
cv2.imshow("image",img_re)
cv2.waitKey(0)
cv2.imshow("abg blur",avg)
cv2.waitKey(0)
cv2.destroyAllWindows()

image bluring - median filter

In [75]:
noi=cv2.imread("noisec.png")

In [76]:
med=cv2.medianBlur(noi,3)


In [68]:
cv2.imshow("before",noi)
cv2.waitKey(0)
cv2.imshow("after",med)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [87]:
bi=cv2.bilateralFilter(noi,15,30,30)

In [88]:
cv2.imshow("before",noi)
cv2.waitKey(0)
cv2.imshow("after",bi)
cv2.waitKey(0)
cv2.destroyAllWindows()