In [1]:
import cv2

In [5]:
img=cv2.imread("noise1.jpeg")

In [6]:
avg=cv2.blur(img,(25,25))

In [9]:
cv2.imshow("be",img)
cv2.waitKey(0)
cv2.imshow("af",avg)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [10]:
med=cv2.medianBlur(img,9)

In [11]:
cv2.imshow("be",img)
cv2.waitKey(0)
cv2.imshow("af",med)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [13]:
cv2.imwrite("no.jpeg",med)

True

In [14]:
cv2.imwrite("no2.jpeg",avg)

True

In [15]:
import numpy as np

In [16]:
ker=np.ones((3,3),float)/9

In [17]:
print(ker)

[[0.11111111 0.11111111 0.11111111]
 [0.11111111 0.11111111 0.11111111]
 [0.11111111 0.11111111 0.11111111]]


In [18]:
df=cv2.filter2D(img,-1,ker)

In [19]:
cv2.imshow("be",img)
cv2.waitKey(0)
cv2.imshow("af",df)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [20]:
cv2.imwrite("2d.jpeg",df)

True

In [21]:
img_re=cv2.resize(img,(200,200))

In [22]:
cv2.imshow("be",img)
cv2.waitKey(0)
cv2.imshow("af",img_re)
cv2.waitKey(0)
cv2.destroyAllWindows()